# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d9b25bc4213d477a790f2ea25bbaba9e5a4aae84416d28ae55e9e2188b27c0b1f3ab76dfcce88d8fad658f086ba68ed53f90e6b966cc2eb01c961a484e97dd

test:
  secret_key_base: b636109a1c072db80e774809f1ff5ad92780f0dbdc89a1c245ac9b0a7faabe0f8e1f91851a6b6f78f7da6999ddf239f6e7bdaf446ccac9a51f6f8bf7d26f0366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
