# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda5e20532aecd12058de7059c08cdc4546ee833c85ebac03034366ac2094b5040725658fefe95a92abf6835ee21893071a484770f38a6275abf694864906e7d

test:
  secret_key_base: 0c0ecc309822233242527df07d350d2030653567d17b06e5ac8c33329ac7648a513d4e83c6fc7562a9c4ab6fa7e855dd7447f5c4798d321cc48c3437325ca31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
